tms/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .forms import LoginForm
from . import views


app_name = 'tms'
urlpatterns = [
    # Homepage
    path('', views.homepage, name='homepage'),

    # User
    path('profile/', views.profile, name='profile'),
    path('login/', LoginView.as_view(authentication_form=LoginForm), name="login"),

    # Project
    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('project/create', views.ProjectCreateView.as_view(), name='project_create'),
    path('project/<int:pk>/detail', views.ProjectDetailView.as_view(), name='project_detail'),
    path('project/<int:pk>/update', views.ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete', views.ProjectDeleteView.as_view(), name='project_delete'),

    # Suite
    path('suite/create', views.SuiteCreateView.as_view(), name='suite_create'),
    path('suite/<int:pk>/detail', views.SuiteDetailView.as_view(), name='suite_detail'),
    path('suite/<int:pk>/update', views.SuiteUpdateView.as_view(), name='suite_update'),
    path('suite/<int:pk>/delete', views.SuiteDeleteView.as_view(), name='suite_delete'),

    # Case
    path('case/create', views.CaseCreateView.as_view(), name='case_create'),
    path('case/<int:pk>/', views.CaseDetailView.as_view(), name='case_detail'),
    path('case/<int:pk>/update', views.CaseUpdateView.as_view(), name='case_update'),
    path('case/<int:pk>/delete', views.CaseDeleteView.as_view(), name='case_delete'),
]

vtms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tms.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls"),),
]

tms/models.py
import datetime

from django.db import models
from django.urls import reverse
from django.utils import timezone


class Project(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tms:project_detail', kwargs={'pk': self.pk})


class Suite(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tms:suite_detail', kwargs={'pk': self.pk})


class Case(models.Model):
    suite = models.ForeignKey(Suite, on_delete=models.CASCADE)
    name = models.CharField(max_length=300)
    description = models.TextField()
    pre_requisites = models.TextField()
    test_steps = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)

    statuses = [
        ('p', 'Passed'),
        ('f', 'Failed'),
        ('n', 'New'),
        ('i', 'In progress')
    ]
    case_status = models.CharField(
        max_length=2,
        choices=statuses,
        default=statuses[-2][1]
    )

    automation_statuses = [
        ('a', 'Automated'),
        ('m', 'Manual')
    ]
    automated = models.CharField(
        max_length=2,
        choices=automation_statuses,
    )

    def get_absolute_url(self):
        return reverse('tms:case_detail', kwargs={'pk': self.pk})

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.name

tms/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import Suite


class SuiteForm(forms.Form):
    class Meta:
        model = Suite

        fields = ['name', 'description']


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'id': 'Username', 'type': 'text', 'placeholder': 'User Name'}
        )
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'id': 'password', 'type': 'password', 'placeholder': 'Password'}
        )

tms/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user
from .models import Project, Suite, Case


class LoginRequired(LoginRequiredMixin):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'


def homepage(request):
    return render(request, 'homepage.html')


@login_required(login_url='/login/')
def profile(request):
    user = get_user(request)
    return render(request, 'registration/profile.html', {'user': user})


class ProjectDetailView(LoginRequired, DetailView):
    model = Project
    template_name = 'tms/project/project_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        context['project_suites'] = Suite.objects.filter(project=self.kwargs.get('pk'))
        return context


class ProjectListView(LoginRequired, ListView):
    model = Project
    template_name = 'tms/project/project_list.html'
    context_object_name = 'projects'


class ProjectCreateView(LoginRequired, CreateView):
    model = Project
    fields = ['name', 'description']
    template_name_suffix = "/project_form"


class ProjectUpdateView(LoginRequired, UpdateView):
    model = Project
    fields = ['name', 'description']
    template_name_suffix = "/project_form"


class ProjectDeleteView(LoginRequired, DeleteView):
    model = Project
    success_url = '/'


class SuiteDetailView(LoginRequired, DetailView):
    model = Suite
    template_name = 'tms/suite/suite_detail.html'

    def get_context_data(self, **kwargs):
        context = super(SuiteDetailView, self).get_context_data(**kwargs)
        context['suite_cases'] = Case.objects.filter(suite=self.kwargs.get('pk'))
        return context


class SuiteCreateView(LoginRequired, CreateView):
    model = Suite
    fields = ['name', 'description', 'project']
    template_name_suffix = "/suite_form"


class SuiteUpdateView(LoginRequired, UpdateView):
    model = Suite
    fields = ['name', 'description']
    template_name_suffix = "/suite_form"


class SuiteDeleteView(LoginRequired, DeleteView):
    model = Suite
    template_name = 'tms/suite/suite_confirm_delete.html'
    success_url = '/'


class CaseDetailView(LoginRequired, DetailView):
    model = Case
    template_name = 'tms/case/case_detail.html'
    context_object_name = 'case'


class CaseCreateView(LoginRequired, CreateView):
    model = Case
    fields = ['suite', 'name', 'description', 'pre_requisites', 'test_steps',
              'case_status', 'automated']
    template_name_suffix = "/case_form"


class CaseUpdateView(LoginRequired, UpdateView):
    model = Case
    fields = ['name', 'description']
    template_name_suffix = "/case_form"


class CaseDeleteView(LoginRequired, DeleteView):
    model = Case
    success_url = '/'

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vigilant Test Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body style="background-color: #eee;">
<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'tms:homepage' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                VTMS
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'tms:homepage' %}" class="nav-link px-2 text-white">Home</a></li>
                <li><a href="{% url 'tms:projects' %}" class="nav-link px-2 text-white">Projects</a></li>
                <li><a href="#" class="nav-link px-2 text-white">About</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control form-control-dark text-bg-white" placeholder="Search..." aria-label="Search">
            </form>

            {% if user.is_authenticated %}
            <div class="dropdown text-end text-light">
                <a href="#" class="d-block text-decoration-none dropdown-toggle text-white" data-bs-toggle="dropdown" aria-expanded="false">
                    Logged as: {{ user.get_username }}
                </a>

                <ul class="dropdown-menu text-small" style="">
                    <li><a class="dropdown-item" href="{% url 'tms:profile' %}">Profile</a></li>
                    <li><a class="dropdown-item" href="{% url 'tms:project_create' %}">New project...</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'logout' %}">Log out</a></li>
                </ul>

            </div>
            {% else %}
            <div class="text-end">
                <a class="btn btn-outline-light me-2" href="{% url 'tms:login' %}">Login</a>
            </div>
            {% endif %}
        </div>
    </div>
</header>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
{% block javascript %}
{% endblock javascript%}
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% block content %}
<div class="container-fluid">
    <div class="row mt-4">
        <div class="col-sm-8">
            <h3>Welcome to Vigilant Test Management System</h3>
            <div class="card">
                <div class="card-body">
                    <p>VTMS - is minimalistic test management system for your project or company.</p>

                    <p>Find more by reading <a href="#">Documentation</a></p>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <h6>Last news</h6>
            <div class="card">
                <div class="card-body">
                    Info:
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tms/templates/tms/case/case_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
       <p class="mt-4"><b>Test suite:</b> {{ case.suite }}</p>
       <p class="text-end">
              <span class="me-4"><b>Status:</b> {{ case.get_case_status_display }}</span>
              <span><b>Pub date:</b> {{ case.pub_date }}</span>
       </p>
       <div class="col-sm-12">
              <h2>Name: {{ case.name }}</h2>
              <p><b>Description:</b> {{ case.description }}</p>
              <p><b>Preconditions:</b> {{ case.pre_requisites }}</p>
              <p><b>Steps:</b> {{ case.test_steps }}</p>
              <p><b>Automated:</b> {{ case.get_automated_display }}</p>
       </div>
       <div class="text-end">
              <a class="btn btn-secondary" href="{% url 'tms:case_update' pk=case.pk %}" role="button">Edit</a>
              <a class="btn btn-danger" href="{% url 'tms:case_delete' pk=case.pk %}" role="button">Delete</a>
       </div>
</div>

{% endblock %}

tms/templates/tms/case/case_form.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data">

	<!-- Security token -->
	{% csrf_token %}

	<!-- Using the formset -->
	{{ form.as_p }}

	<input type="submit" value="Submit">
</form>
{% endblock %}

tms/templates/tms/case_detail.html
<a href="{% url 'tms:index'  %}">Home</a>
<p>Test suite: {{ case.suite }}</p>
<p>Name: {{ case.name }}</p>
<p>Description: {{ case.description }}</p>
<p>Pre: {{ case.pre_requisites }}</p>
<p>Steps: {{ case.test_steps }}</p>
<p>Pub date: {{ case.pub_date }}</p>
<p>Status: {{ case.get_case_status_display }}</p>
<p>Automated: {{ case.get_automated_display }}</p>

tms/templates/tms/index.html
{% extends 'tms/base.html' %}

{% block content %}
    {% if suites %}
    <ul class="list-group">
        {% for suite in suites %}
        <li class="list-group-item"><a href="{% url 'tms:suite_detail' suite.id %}">{{ suite.name }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No suites are available.</p>
    {% endif %}
{% endblock %}

tms/templates/tms/project/project_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-sm-12 mt-3 text-end">
        <a class="btn btn-success" href="{% url 'tms:suite_create' %}" role="button">Create suite</a>
    </div>
    {% if project_suites %}
    <div class="col-sm-12 mt-4">
        <h2>Suites</h2>
    </div>
    {% for suite in project_suites %}
    <div class="card mt-3">
        <h5 class="card-header">Suite: {{ suite.name }}</h5>
        <div class="card-body">
            <p class="card-text">{{ suite.description }}</p>
            <a href="{% url 'tms:suite_detail' suite.id %}" class="btn btn-primary">Check suite</a>

            <div class="text-end">
                <a class="btn btn-secondary" href="{% url 'tms:suite_update' pk=suite.pk %}" role="button">Edit</a>
                <a class="btn btn-danger" href="{% url 'tms:suite_delete' pk=suite.pk %}" role="button">Delete</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
        <p>No suites are available.</p>
    {% endif %}
{% endblock %}

tms/templates/tms/project/project_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h2>Edit project:</h2>
		<form method="POST" enctype="multipart/form-data">

			<!-- Security token -->
			{% csrf_token %}

			<!-- Using the formset -->
			{{ form.as_p }}

			<input type="submit" value="Submit">
		</form>
	</div>
</div>
{% endblock %}

tms/templates/tms/project/project_list.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12 mt-3 text-end">
        <a class="btn btn-success" href="{% url 'tms:project_create' %}" role="button">Add new project</a>
    </div>
    {% if projects %}
    <div class="col-sm-12">
        <h2>Projects</h2>
    </div>
    {% for project in projects %}
    <div class="col-sm-6">
        <div class="card mt-3">
            <h5 class="card-header">{{ project.name }}</h5>
            <div class="card-body">
                <p class="card-text">{{ project.description }}</p>
                <a href="{% url 'tms:project_detail' project.id %}" class="btn btn-primary">Go to the project</a>

                <div class="text-end">
                    <a class="btn btn-secondary" href="{% url 'tms:project_update' pk=project.pk %}" role="button">Edit</a>
                    <a class="btn btn-danger" href="{% url 'tms:project_delete' pk=project.pk %}" role="button">Delete</a>
                </div>

            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>No projects are available.</p>
    {% endif %}
</div>
{% endblock %}

tms/templates/tms/suite/suite_confirm_delete.html
<form action="{% url 'tms:suite_delete' pk=suite.pk %}" method="POST">
       {% csrf_token %}
       <button class="btn">Delete</button>
</form>

tms/templates/tms/suite/suite_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="mt-4">
    <h2>{{ suite.name }}</h2>
    <p>Description: {{ suite.description }}</p>
</div>

<table class="table">
    <thead>
    <tr>
        <th scope="col">#id</th>
        <th scope="col">Name</th>
        <th scope="col">Status</th>
        <th scope="col">Automated</th>
        <th scope="col">Pub date</th>
    </tr>
    </thead>
    <tbody>
    {% for case in suite_cases %}
    <tr>
        <th scope="row">{{ case.pk }}</th>
        <td><a href="{% url 'tms:case_detail' case.id %}">{{ case.name }}</a></td>
        <td>{{ case.get_case_status_display }}</td>
        <td>{{ case.get_automated_display }}</td>
        <td>{{ case.pub_date }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

tms/templates/tms/suite/suite_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
	<div class="col-sm-12">
		<h2>Edit suite:</h2>

		<form method="POST" enctype="multipart/form-data">

			<!-- Security token -->
			{% csrf_token %}

			<!-- Using the formset -->
			{{ form.as_p }}

			<input type="submit" value="Submit">
		</form>
	</div>
</div>
{% endblock %}